name: C/C++ CI

on: push

jobs:
  build:
    runs-on: linux
    container: archlinux
    steps:
    - uses: actions/checkout@v2
    - uses: actions/hello-world-docker-action@master
      with:
        who-to-greet: 'Mona the Octocat'
    
    - name: configure
      run: echo hi; ls; df -h; pwd; cat /proc/cpuinfo; free
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
